### ISSUE TITLE
Test scheduling of sending messages to Actors

### ISSUE THREAD

**Issue by Tibolte** [miguno/akka-mock-scheduler#11]
I have a case where I have to delay some action with `akka.scheduler`, and this action is basically sending a message to an `ActorRef`. This is all documented [here].(http://doc.akka.io/docs/akka/snapshot/scala/scheduler.html)

In this link you can find this code snippet:

```scala
val Tick = "tick"
class TickActor extends Actor {
  def receive = {
    case Tick => //Do something
  }
}
val tickActor = system.actorOf(Props(classOf[TickActor], this))
//Use system's dispatcher as ExecutionContext
import system.dispatcher

//This will schedule to send the Tick-message
//to the tickActor after 0ms repeating every 50ms
val cancellable =
  system.scheduler.schedule(
    0 milliseconds,
    50 milliseconds,
    tickActor,
    Tick)

//This cancels further Ticks to be sent
cancellable.cancel()

```

Your library presents a neat way of testing scheduling with Akka, but I'm having a hard time tiding it to testing scheduling with Actors. Is that something doable or not supported?

**Comment by miguno** [comment]
I haven't tried it with Actors yet.

I suppose the following won't work because the (mock) scheduler is not tied to `system`, which also controls `system.dispatcher`?

```scala
val tickActor = system.actorOf(Props(classOf[TickActor], this))

//Use system's dispatcher as ExecutionContext
import system.dispatcher

// From akka-mock-scheduler
val time = new VirtualTime

val cancellable =
  time.scheduler.schedule( // <<< note the use of `time.scheduler`
    0 milliseconds,
    50 milliseconds,
    tickActor,
    Tick)

```

http://doc.akka.io/docs/akka/snapshot/scala/scheduler.html also says:
> When scheduling periodic or single messages in an actor to itself it is recommended to use the [Actor Timers](http://doc.akka.io/docs/akka/snapshot/scala/actors.html#actors-timers) instead of using the `Scheduler` directly.

**Comment by Tibolte** [comment]
@miguno thanks for the answer, I'm gonna investigate actor timers and see what I can do.

**Comment by miguno** [comment]
Closed because of inactivity.  Feel free to reopen if needed.
